services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    depends_on:
      - mariadb
    environment:
      APP_URL: "http://app:80"
      # Application
      APP_ENV: "dev"
      APP_SECRET: "a9806d99cd5c1503d8af30c963c9411f"
      DATABASE_URL: "mysql://user:password@mariadb:3306/notifications"
  mariadb:
    image: 'mariadb:10.6'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "notifications"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
